name: serv00-ssh-login-action.py

on:
  # schedule:
    # - cron: '0 8 * * *' # 每天一次
    # - cron: '0 8 * * 0' #每周日一次
  workflow_dispatch: # 支持手动执行

jobs:
  serv00-ssh-login-action:
    runs-on: ubuntu-latest

    steps:
      - name: 迁出代码
        uses: actions/checkout@v4

      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装软件
        run: |
          pip install paramiko requests

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
      - name: 运行脚本
        run: |
          python run.py
